## Limpeza do dataset "iris-com-erros.csv" com diferentes abordagens

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# carregamento do csv com erros
data = pd.read_csv('../data/iris-with-errors.csv')
print(f"número de linhas e de colunas {data.shape}")
data.head(10)

número de linhas e de colunas (25, 5)

  sepal_length sepal_width  petal_length petal_width    species
0          5.1         3.5           1.4         0.2  duplicada
1          5.1         3.5           1.4         0.2  duplicada
2            ?           3           1.4         0.2     setosa
3          4.7         3.2           1.3         0.2     setosa
4          5.1         3.5           1.4         0.2  duplicada
5          NaN         3.1           1.5         0.2     setosa
6            5         3.6           1.4         0.2     setosa
7          5.4         3.9           1.7         0.4  duplicada
8          5.4         3.9           1.7         0.4  duplicada
9          4.6         3.4           1.4         NaN     setosa

### Abordagem com apagamento das linhas com falta de valores

In [3]:
data_sem_nan = data.replace('?', np.nan) # substitui valores '?' por NaN
data_sem_nan = data_sem_nan.dropna() # dropa valores NaN
print(f"número de linhas e de colunas {data_sem_nan.shape}")

número de linhas e de colunas (19, 5)

In [4]:
data_sem_duplicate = data_sem_nan.drop_duplicates() # dropa duplicates
print(f"número de linhas e de colunas {data_sem_duplicate.shape}")

número de linhas e de colunas (14, 5)

### Abordagem com substituição dos valores faltantes pela média

In [41]:
data_faltante_como_media = data.replace('?', np.nan) # substitui valores '?' por NaN
data_faltante_como_media.head(25)
cols_numericas = []

# pega as colunas numéricas
for col in data_faltante_como_media.columns:
    if col != 'species':
        cols_numericas.append(col)

# calcula a média de cada uma das colunas numéricas (convertidas para float)
media_colunas = np.nanmean(np.array(data_faltante_como_media[cols_numericas], dtype=float), axis=0) 

# substitui os valores NaN pela média da coluna
for col in cols_numericas:
    data_faltante_como_media[col] = data_faltante_como_media[col].fillna(media_colunas[cols_numericas.index(col)])

# dropa duplicatas
data_faltante_como_media = data_faltante_como_media.drop_duplicates()

data_faltante_como_media.head(10)

   sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
2      5.022727           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
5      5.022727         3.1           1.5         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
9           4.6         3.4           1.4    0.226087     setosa
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa

In [ ]:
# para responder uma das perguntas do questionário, precisamos das medianas das colunas preenchidas por média
mediana_colunas = np.nanmedian(np.array(data_faltante_como_media[cols_numericas], dtype=float), axis=0)
print(f"mediana das colunas numéricas: {mediana_colunas}")

mediana das colunas numéricas: [5.02272727 3.41875    1.4        0.2       ]